# SPDX-FileCopyrightText: 2024 Ferenc Nandor Janky <ferenj@effective-range.com>
# SPDX-FileCopyrightText: 2024 Attila Gombos <attila.gombos@effective-range.com>
# SPDX-License-Identifier: MIT

from enum import Enum


class WifiEventType(Enum):
    CLIENT_STARTED = 'CLIENT_STARTED'
    CLIENT_STOPPED = 'CLIENT_STOPPED'
    CLIENT_FAILED = 'CLIENT_FAILED'
    CLIENT_DISABLED = 'CLIENT_DISABLED'
    CLIENT_INACTIVE = 'CLIENT_INACTIVE'
    CLIENT_SCANNING = 'CLIENT_SCANNING'
    CLIENT_CONNECTING = 'CLIENT_CONNECTING'
    CLIENT_CONNECTED = 'CLIENT_CONNECTED'
    CLIENT_DISCONNECTED = 'CLIENT_DISCONNECTED'
    CLIENT_IP_ACQUIRED = 'CLIENT_IP_ACQUIRED'

    HOTSPOT_STARTED = 'HOTSPOT_STARTED'
    HOTSPOT_STOPPED = 'HOTSPOT_STOPPED'
    HOTSPOT_FAILED = 'HOTSPOT_FAILED'
    HOTSPOT_PEER_CONNECTED = 'HOTSPOT_PEER_CONNECTED'
    HOTSPOT_PEER_RECONNECTED = 'HOTSPOT_PEER_RECONNECTED'
    HOTSPOT_PEER_DISCONNECTED = 'HOTSPOT_PEER_DISCONNECTED'

    def __repr__(self) -> str:
        return self.value
